# volumes:
#   db:
services:
  db:
    container_name: db
    image: mongo #:4.0.4
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongod.conf:/etc/mongod.conf 

  app:
    container_name: app
    build: ./app/app
    restart: always
    ports:
      - "80:3000"
    environment:
      - DB_HOST=mongodb://db:27017/posts
    depends_on:
      - db