apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # what kind of service/object you want to create

# what would you like to call it - name the service/object
metadata:
  name: nginx-deployment
spec: 
  selector:
    matchLabels:
      app: nginx # look for this label to match with k8 service
  
  # create 3 replica sets of this pod
  replicas: 3
  # template to use it's label for k8 service to launch in the browser
  template: 
    metadata:
      labels:
        app: nginx
   # let's define the container spec
    spec:
      containers:
      - name: nginx
        image: benedek4000/nginx-cv:latest
        ports:
        - containerPort: 80