apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-app-deployment

spec: 
  selector:
    matchLabels:
      app: sparta-app
  
  replicas: 3

  template:
    metadata:
      labels:
        app: sparta-app
    
    spec:
      containers:
      - image: agelemerov/eng130-angel-docker:latest
        imagePullPolicy: Always
        name: eng130-angel-docker
        ports: 
        - containerPort: 3000